language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=bPF6cW1cKVSWrpFjRmCo6X9GvkrlcEaY
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - php artisan migrate --force

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
